### ISSUE TITLE
Regions flags no longer work

### ISSUE THREAD

**Issue by SirCypkowskyy** [amckenna41/iso3166-2#18]
While attempting to use the Python package, I noticed that the links to the region flags no longer function - the `iso3166-2-icons` repository itself was hidden.

Therefore, are there any alternative methods to fetch the flags for each region? Will the repository be made public again? And if not, is there an option to use links to wikimedia files instead of links to the closed repository? Perhaps you might have a CSV file with such data mapping?

**Comment by amckenna41** [comment]
Hey Cyprian,

Just following up to see if your issue has been resolved & if you're facing any other issues with the iso3166-2 software. I've just released the latest version of the software v1.7.2
https://github.com/amckenna41/iso3166-2/tree/main/iso3166_2#TOP

Thank you!
[https://opengraph.githubassets.com/ec972d7940a95c68bb5414d1d1fff17c4055988cb92c54e45a54e970ba65a91b/amckenna41/iso3166-2]<https://github.com/amckenna41/iso3166-2/tree/main/iso3166_2#TOP>
iso3166-2/iso3166_2 at main · amckenna41/iso3166-2<https://github.com/amckenna41/iso3166-2/tree/main/iso3166_2#TOP>
A lightweight Python package, and accompanying RESTful API, for accessing all of the world&#39;s most up-to-date and accurate ISO 3166-2 subdivision data, including: name, local/other name, parent ...
github.com

________________________________
